import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const questions = [
  {
    id: "q001_company_description",
    block: "BLOQUE 0 — CONTEXTO GENERAL",
    title: "¿Cuál es el nombre de la empresa y a qué se dedica en una oración?",
    inputType: "short_text",
    order: 1,
    isBaseline: false,
  },
  {
    id: "q002_business_age",
    block: "BLOQUE 0 — CONTEXTO GENERAL",
    title: "¿Cuántos años lleva operando el negocio? Si es menos de un año, indique los meses.",
    inputType: "short_text",
    order: 2,
    isBaseline: false,
  },
  {
    id: "q003_business_stage",
    block: "BLOQUE 0 — CONTEXTO GENERAL",
    title: "¿En qué etapa considera que se encuentra el negocio actualmente? Arranque / Crecimiento / Consolidación / Expansión",
    inputType: "single_choice",
    order: 3,
    isBaseline: false,
  },
  {
    id: "q004_team_size",
    block: "BLOQUE 0 — CONTEXTO GENERAL",
    title: "¿Cuántas personas trabajan en la empresa incluyendo socios, empleados y colaboradores?",
    inputType: "number",
    order: 4,
    isBaseline: false,
  },
  {
    id: "q005_main_challenge",
    block: "BLOQUE 0 — CONTEXTO GENERAL",
    title: "En una sola oración: ¿cuál es el mayor problema o reto que enfrenta hoy el negocio?",
    inputType: "long_text",
    order: 5,
    isBaseline: false,
  },
  {
    id: "q006_monthly_transactions",
    block: "BLOQUE 1 — MÉTRICAS BASE",
    title: "¿Cuántas operaciones o transacciones de venta realiza al mes en promedio?",
    inputType: "number_or_range",
    order: 6,
    isBaseline: true,
  },
  {
    id: "q007_monthly_revenue",
    block: "BLOQUE 1 — MÉTRICAS BASE",
    title: "¿Cuál es el monto total de ventas o ingresos mensuales aproximados?",
    inputType: "currency_or_range",
    order: 7,
    isBaseline: true,
  },
  {
    id: "q008_average_ticket",
    block: "BLOQUE 1 — MÉTRICAS BASE",
    title: "¿Cuál es el ticket promedio por venta o transacción?",
    inputType: "currency",
    order: 8,
    isBaseline: true,
  },
  {
    id: "q009_active_clients",
    block: "BLOQUE 1 — MÉTRICAS BASE",
    title: "¿Cuántos clientes activos tiene actualmente — clientes que han comprado en los últimos 90 días?",
    inputType: "number",
    order: 9,
    isBaseline: true,
  },
  {
    id: "q010_repeat_customer_percentage",
    block: "BLOQUE 1 — MÉTRICAS BASE",
    title: "¿Qué porcentaje aproximado de sus ventas proviene de clientes que regresan a comprar de nuevo?",
    inputType: "percentage",
    order: 10,
    isBaseline: true,
  },
  {
    id: "q011_customer_channels",
    block: "BLOQUE 2 — GENERACIÓN DE DEMANDA",
    title: "¿Por qué canales llegan la mayoría de sus clientes hoy? Redes sociales / Referidos / Publicidad pagada / Búsqueda en Google / Tráfico físico / Otro",
    inputType: "multiple_choice",
    order: 11,
    isBaseline: false,
  },
  {
    id: "q012_marketing_budget",
    block: "BLOQUE 2 — GENERACIÓN DE DEMANDA",
    title: "¿Tienen presupuesto definido para atraer clientes? ¿Cuánto invierten al mes aproximadamente en marketing o publicidad?",
    inputType: "text_number",
    order: 12,
    isBaseline: false,
  },
  {
    id: "q013_customer_acquisition_cost",
    block: "BLOQUE 2 — GENERACIÓN DE DEMANDA",
    title: "¿Saben cuánto les cuesta conseguir un cliente nuevo — su costo de adquisición?",
    inputType: "single_choice",
    order: 13,
    isBaseline: true,
  },
  {
    id: "q014_best_customer_channel",
    block: "BLOQUE 2 — GENERACIÓN DE DEMANDA",
    title: "¿Han identificado qué canal o fuente genera los mejores clientes — no los más baratos sino los más valiosos?",
    inputType: "long_text",
    order: 14,
    isBaseline: false,
  },
  {
    id: "q015_new_customers_trend",
    block: "BLOQUE 2 — GENERACIÓN DE DEMANDA",
    title: "En los últimos 3 meses, ¿el número de clientes nuevos aumentó, se mantuvo igual o disminuyó? ¿Saben por qué?",
    inputType: "long_text",
    order: 15,
    isBaseline: false,
  },
  {
    id: "q016_sales_process",
    block: "BLOQUE 3 — PROCESO COMERCIAL",
    title: "¿Tienen un proceso definido desde que un prospecto muestra interés hasta que compra? ¿Cuántos pasos tiene?",
    inputType: "long_text",
    order: 16,
    isBaseline: false,
  },
  {
    id: "q017_response_time",
    block: "BLOQUE 3 — PROCESO COMERCIAL",
    title: "¿Cuánto tiempo pasa en promedio desde que un cliente potencial contacta el negocio hasta que recibe respuesta?",
    inputType: "single_choice",
    order: 17,
    isBaseline: false,
  },
  {
    id: "q018_conversion_rate",
    block: "BLOQUE 3 — PROCESO COMERCIAL",
    title: "¿De cada 10 personas que muestran interés en comprar, cuántas terminan comprando efectivamente?",
    inputType: "number",
    order: 18,
    isBaseline: true,
  },
  {
    id: "q019_lost_sale_reason",
    block: "BLOQUE 3 — PROCESO COMERCIAL",
    title: "¿Cuál es la principal razón por la que alguien interesado decide no comprar? ¿Lo saben con datos o es una suposición?",
    inputType: "long_text",
    order: 19,
    isBaseline: false,
  },
  {
    id: "q020_follow_up_process",
    block: "BLOQUE 3 — PROCESO COMERCIAL",
    title: "¿Hacen seguimiento a clientes que no compraron la primera vez? Si sí, ¿cómo lo hacen?",
    inputType: "single_choice_text",
    order: 20,
    isBaseline: false,
  },
  {
    id: "q021_top_products",
    block: "BLOQUE 4 — PRODUCTO Y PRECIO",
    title: "¿Cuáles son sus 2 o 3 productos o servicios que más se venden? ¿Qué porcentaje de las ventas representan?",
    inputType: "long_text",
    order: 21,
    isBaseline: false,
  },
  {
    id: "q022_pricing_method",
    block: "BLOQUE 4 — PRODUCTO Y PRECIO",
    title: "¿Cómo definen sus precios actualmente? Costo + margen / Precio de mercado / Lo que el cliente paga / No hay criterio claro",
    inputType: "single_choice",
    order: 22,
    isBaseline: false,
  },
  {
    id: "q023_price_increase",
    block: "BLOQUE 4 — PRODUCTO Y PRECIO",
    title: "¿Han subido precios en el último año? ¿Cuánto? ¿Cómo reaccionaron los clientes?",
    inputType: "long_text",
    order: 23,
    isBaseline: false,
  },
  {
    id: "q024_differentiation",
    block: "BLOQUE 4 — PRODUCTO Y PRECIO",
    title: "¿Tienen claro qué los diferencia de su competencia directa — por qué un cliente debería elegirlos a ellos?",
    inputType: "long_text",
    order: 24,
    isBaseline: false,
  },
  {
    id: "q025_new_offer_opportunity",
    block: "BLOQUE 4 — PRODUCTO Y PRECIO",
    title: "¿Qué producto o servicio nuevo podrían ofrecer que sus clientes actuales les estarían pidiendo o necesitando?",
    inputType: "long_text",
    order: 25,
    isBaseline: false,
  },
  {
    id: "q026_customer_database",
    block: "BLOQUE 5 — CLIENTES Y RETENCIÓN",
    title: "¿Tienen una base de datos organizada de sus clientes con información de contacto?",
    inputType: "single_choice",
    order: 26,
    isBaseline: false,
  },
  {
    id: "q027_post_purchase_communication",
    block: "BLOQUE 5 — CLIENTES Y RETENCIÓN",
    title: "¿Se comunican activamente con sus clientes después de que compran? ¿Cómo y con qué frecuencia?",
    inputType: "long_text",
    order: 27,
    isBaseline: false,
  },
  {
    id: "q028_inactive_customers",
    block: "BLOQUE 5 — CLIENTES Y RETENCIÓN",
    title: "¿Saben cuántos clientes que compraron una vez no han vuelto a comprar? ¿Hacen algo al respecto?",
    inputType: "long_text",
    order: 28,
    isBaseline: false,
  },
  {
    id: "q029_referrals",
    block: "BLOQUE 5 — CLIENTES Y RETENCIÓN",
    title: "¿Qué hace que un cliente los recomiende a alguien más? ¿Tienen algún programa de referidos?",
    inputType: "long_text",
    order: 29,
    isBaseline: false,
  },
  {
    id: "q030_top_client_risk",
    block: "BLOQUE 5 — CLIENTES Y RETENCIÓN",
    title: "Si sus mejores 5 clientes dejaran de comprar mañana, ¿cuánto impacto tendría en sus ingresos totales?",
    inputType: "percentage_or_currency",
    order: 30,
    isBaseline: false,
  },
  {
    id: "q031_owner_dependency",
    block: "BLOQUE 6 — OPERACIÓN Y EQUIPO",
    title: "¿Qué pasaría con el negocio si el dueño o persona clave no pudiera trabajar por 30 días?",
    inputType: "long_text",
    order: 31,
    isBaseline: false,
  },
  {
    id: "q032_documented_processes",
    block: "BLOQUE 6 — OPERACIÓN Y EQUIPO",
    title: "¿Los procesos principales del negocio están documentados — escritos o en manuales?",
    inputType: "single_choice",
    order: 32,
    isBaseline: false,
  },
  {
    id: "q033_operational_bottlenecks",
    block: "BLOQUE 6 — OPERACIÓN Y EQUIPO",
    title: "¿Cuáles son los 2 o 3 cuellos de botella operativos más frecuentes?",
    inputType: "long_text",
    order: 33,
    isBaseline: false,
  },
  {
    id: "q034_management_tools",
    block: "BLOQUE 6 — OPERACIÓN Y EQUIPO",
    title: "¿Usan alguna herramienta de gestión — software, CRM, app, hoja de control? ¿Cuál?",
    inputType: "long_text",
    order: 34,
    isBaseline: false,
  },
  {
    id: "q035_owner_time_allocation",
    block: "BLOQUE 6 — OPERACIÓN Y EQUIPO",
    title: "¿Cuánto tiempo dedica el dueño a tareas operativas del día a día vs a pensar y planear el crecimiento del negocio?",
    inputType: "percentage_estimate",
    order: 35,
    isBaseline: false,
  },
  {
    id: "q036_net_margin",
    block: "BLOQUE 7 — FINANZAS Y RENTABILIDAD",
    title: "¿Saben cuál es su margen de ganancia neta aproximado — lo que queda después de todos los costos?",
    inputType: "single_choice_estimate",
    order: 36,
    isBaseline: true,
  },
  {
    id: "q037_business_personal_finances",
    block: "BLOQUE 7 — FINANZAS Y RENTABILIDAD",
    title: "¿Tienen separadas las finanzas del negocio de las finanzas personales del dueño?",
    inputType: "single_choice",
    order: 37,
    isBaseline: false,
  },
  {
    id: "q038_cash_flow_health",
    block: "BLOQUE 7 — FINANZAS Y RENTABILIDAD",
    title: "¿El negocio genera suficiente flujo de efectivo para cubrir gastos del mes sin depender de ventas futuras?",
    inputType: "single_choice",
    order: 38,
    isBaseline: false,
  },
  {
    id: "q039_largest_fixed_cost",
    block: "BLOQUE 7 — FINANZAS Y RENTABILIDAD",
    title: "¿Cuál es el mayor gasto fijo mensual del negocio — el que más pesa aunque no vendan nada?",
    inputType: "text_currency",
    order: 39,
    isBaseline: false,
  },
  {
    id: "q040_12_month_goal",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "¿Cuál es el objetivo más importante del negocio para los próximos 12 meses — en números concretos?",
    inputType: "long_text",
    order: 40,
    isBaseline: false,
  },
  {
    id: "q041_main_blocker",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "¿Qué está impidiendo hoy que ese objetivo ya se esté cumpliendo?",
    inputType: "long_text",
    order: 41,
    isBaseline: false,
  },
  {
    id: "q042_previous_attempts",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "¿Han intentado antes resolver el problema principal? ¿Qué intentaron y por qué no funcionó?",
    inputType: "long_text",
    order: 42,
    isBaseline: false,
  },
  {
    id: "q043_second_operator",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "¿Existe alguien en el negocio además del dueño que entienda la operación completa?",
    inputType: "single_choice",
    order: 43,
    isBaseline: false,
  },
  {
    id: "q044_postponed_decision",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "¿Qué decisión comercial o de negocio han estado postergando que saben que necesitan tomar?",
    inputType: "long_text",
    order: 44,
    isBaseline: false,
  },
  {
    id: "q045_capacity_to_act",
    block: "BLOQUE 8 — VISIÓN Y SIGUIENTE NIVEL",
    title: "Si el diagnóstico identificara que el problema principal está en un área específica del negocio — ventas, operación, precios, equipo — ¿están en posición de actuar sobre eso?",
    inputType: "long_text",
    order: 45,
    isBaseline: false,
  },
];

async function main() {
  for (const question of questions) {
    await prisma.question.upsert({
      where: { id: question.id },
      update: question,
      create: question,
    });
  }

  console.log(`Seed completed. Inserted/updated ${questions.length} questions.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
